"""Where the NeuroImage: Reports figures go, and what they are called there.

The figure generators grew descriptive filenames (fig6_construct_validity.png)
while the manuscript refers to figures by position (fig6.png). Keeping the two
in step by hand is how a caption ends up describing a different plot, so the
mapping lives here and every generator writes through it.

Figure 2 is the pipeline schematic, which is drawn by make_arch_figure.py and is
not regenerated from results.
"""

from __future__ import annotations

from pathlib import Path

OUT = Path(__file__).resolve().parents[2] / "mri-bsc/paper/neuroimage_clinical"

# descriptive name used by the generator -> name the manuscript includes.
# The order here is the order the figures are declared in the manuscript, which
# is what LaTeX numbers them by.
MANUSCRIPT_NAME = {
    "fig_splot_cohort": "fig1",          # make_splot.py
    "nireports_arch": "fig2",            # nireports_arch.py
    "fig1_model_comparison": "fig3",     # make_model_comparison.py
    "fig2_kaplan_meier": "fig4",         # make_v3_figures.py
    "fig4_design_effect": "fig5",        # make_v3_figures.py
    "nireports_forest": "fig6",          # nireports_forest.py
    "nireports_convergent": "fig7",      # nireports_convergent.py
}

# Still generated by the older scripts, deliberately out of the manuscript.
#   fig5_increment          the increment is Table 4 and now Figure 6
#   fig6_construct_validity folded into the convergent panel, Figure 7
#   fig0_architecture       superseded by nireports_arch.py
NOT_IN_MANUSCRIPT = {"fig5_increment", "fig6_construct_validity",
                     "fig0_architecture"}


def target(name: str) -> Path | None:
    """Path to write `name` to, or None if the manuscript does not include it."""
    if name in NOT_IN_MANUSCRIPT:
        return None
    return OUT / f"{MANUSCRIPT_NAME[name]}.png"
